<?xml version="1.0" encoding="UTF-8"?>

<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.duosecurity</groupId>
  <artifactId>duo-client-all</artifactId>
  <version>0.7.2-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>Duo Security API client and examples</name>
  <description>Two Factor Authentication API Examples</description>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <version.dependency-check-maven>12.2.2</version.dependency-check-maven>
  </properties>
  <modules>
    <module>duo-client</module>
    <module>duo-example-admin</module>
  </modules>

  <repositories>
  </repositories>

  <build>
    <plugins>
      <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <version>${version.dependency-check-maven}</version>
        <configuration>
          <!-- <failBuildOnCVSS>8</failBuildOnCVSS> -->
          <nvdApiKey>${nvd.api.key}</nvdApiKey>
          <ossIndexServerId>ossindex</ossIndexServerId>
          <scanPlugins>false</scanPlugins>
          <autoUpdate>true</autoUpdate>
        </configuration>
        <inherited>false</inherited>
        <executions>
          <execution>
            <id>aggregate-check</id>
            <phase>compile</phase>
            <goals>
              <goal>aggregate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
